parameters:
  - name: buildCommand
    type: string
  - name: artifactName
    type: string
    default: "publishArtifactDrop"
  - name: vmImageName
    type: string
    default: "ubuntu-latest"

jobs:
  - job: build_job
    displayName: "Build projects"
    pool:
      vmImage: ${{ parameters.vmImageName }}
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "18.x"
        displayName: "Install Node.js"

      - task: Npm@1
        displayName: "Install  npm"
        inputs:
          command: "install"

      - task: Bash@3
        displayName: "Build project"
        inputs:
          targetType: "inline"
          script: |
            npm run ${{ parameters.buildCommand }}

      - task: ArchiveFiles@2
        displayName: "Archive files"
        inputs:
          rootFolderOrFile: "$(System.DefaultWorkingDirectory)/dist/"
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
          artifactName: ${{ parameters.artifactName }}
