# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting .NET9.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# *** Pipeline variables ***
# buildEnv - Environment to build the image for (local | dev | uat | prod)

name: $(Build.BuildId)

trigger:
  - none

resources:
  - repo: self

variables:
  vmImageName: "ubuntu-latest" # Agent VM image name
  imageName: scfrontend.web # Your image name
  dockerfile: Dockerfile # Your Dockerfile path

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Image
    jobs:
      - job: DEV
        displayName: Build dev
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/gnx_fix_variable_name')
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              repository: $(imageName)
              tags: "$(Build.BuildId),latest" # Use build number as tag
              dockerfile: $(dockerfile)
              buildArgs: "--build-arg BUILD_ENV=dev" # Pass the the build argument
              containerRegistry: "AcrDevelopmentConnection"

          - task: Docker@2
            displayName: Push
            inputs:
              command: push
              repository: $(imageName)
              tags: "$(Build.BuildId),latest" # Use build number as tag
              containerRegistry: "AcrDevelopmentConnection"

      - job: UAT
        displayName: Build uat
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/uat')
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              repository: $(imageName)
              tags: "$(Build.BuildId),latest" # Use build number as tag
              dockerfile: $(dockerfile)
              buildArgs: "--build-arg BUILD_ENV=uat" # Pass the the build argument
              containerRegistry: "AcrUatConnection"

          - task: Docker@2
            displayName: Push
            inputs:
              command: push
              repository: $(imageName)
              tags: "$(Build.BuildId),latest" # Use build number as tag
              containerRegistry: "AcrUatConnection"

      - job: PROD
        displayName: Build prod
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              repository: $(imageName)
              tags: "$(Build.BuildId),latest" # Use build number as tag
              dockerfile: $(dockerfile)
              buildArgs: "--build-arg BUILD_ENV=prod" # Pass the the build argument
              containerRegistry: "AcrProductionConnection"

          - task: Docker@2
            displayName: Push
            inputs:
              command: push
              repository: $(imageName)
              tags: "$(Build.BuildId),latest" # Use build number as tag
              containerRegistry: "AcrProductionConnection"
